### ISSUE TITLE
Rasi & Other details.. 25th April 2024 9:20 AM Mumbai

### ISSUE THREAD

**Issue by FinAstro** [diliprk/VedicAstro#1]
Hi.. As I compare the astrosage data versus the code data after changing vedicastrostudy.ipyb file, input elements.. while planetary positions are nearly accurate.. the rasi and other details are not..

e.g. Moon is shown to be in 5th house with deg 204.. Rashi is Libra. However in the function.. planets_df, the rashi for moon is shown to be Leo and then all other calculations..

Can you please check...

**Comment by diliprk** [comment]
AstroSage and most other websites might be using an older version of the swiss ephemeris files and software, so their values might be wrong. Extensive tests have already been performed with different ephemeris even using the raw `pyswisseph` package and comparing it with `flatlib` package. Our results are correct!
https://github.com/diliprk/VedicAstro/blob/main/test_suite/deg_var_check_planets.ipynb

If you find any flaw in our logic, you can debug the code and raise a pull request. 

Its also possible you did not give the correct inputs, like `utc`
For further clarifications reach out to me privately

**Comment by FinAstro** [comment]
thanks Dilip for your reply


As i said, the degrees are near accurate.

Whats your contact details? I can send you the analysis

Thanks & Regards

Santosh Rangnekar
9819568713
