### ISSUE TITLE
KP SubLord Division CSV Errors

### ISSUE THREAD

**Issue by OmegaChild** [diliprk/VedicAstro#3]
- All stray colons removed from degree entries.
- Nakshatra names replaced Devanagari or diacritic characters with standard English letters.
- Degree ranges corrected for consistency within each Rashi.
- The data is now accurate and properly formatted.

Sign,Nakshatra,From_DMS,To_DMS,RasiLord,NakshatraLord,SubLord
Aries,Ashvini,00:00:00,00:46:40,Mars,Ketu,Ketu
Aries,Ashvini,00:46:40,03:00:00,Mars,Ketu,Venus
Aries,Ashvini,03:00:00,03:40:00,Mars,Ketu,Sun
Aries,Ashvini,03:40:00,04:46:40,Mars,Ketu,Moon
Aries,Ashvini,04:46:40,05:33:20,Mars,Ketu,Mars
Aries,Ashvini,05:33:20,07:33:20,Mars,Ketu,Rahu
Aries,Ashvini,07:33:20,09:20:00,Mars,Ketu,Jupiter
Aries,Ashvini,09:20:00,11:26:40,Mars,Ketu,Saturn
Aries,Ashvini,11:26:40,13:20:00,Mars,Ketu,Mercury
Aries,Bharani,13:20:00,15:33:20,Mars,Venus,Venus
Aries,Bharani,15:33:20,16:13:20,Mars,Venus,Sun
Aries,Bharani,16:13:20,17:20:00,Mars,Venus,Moon
Aries,Bharani,17:20:00,18:06:40,Mars,Venus,Mars
Aries,Bharani,18:06:40,20:06:40,Mars,Venus,Rahu
Aries,Bharani,20:06:40,21:53:20,Mars,Venus,Jupiter
Aries,Bharani,21:53:20,24:00:00,Mars,Venus,Saturn
Aries,Bharani,24:00:00,25:53:20,Mars,Venus,Mercury
Aries,Bharani,25:53:20,26:40:00,Mars,Venus,Ketu
Aries,Krittika,26:40:00,27:20:00,Mars,Sun,Sun
Aries,Krittika,27:20:00,28:26:40,Mars,Sun,Moon
Aries,Krittika,28:26:40,29:13:20,Mars,Sun,Mars
Aries,Krittika,29:13:20,30:00:00,Mars,Sun,Rahu
Taurus,Krittika,00:00:00,01:13:20,Venus,Sun,Rahu
Taurus,Krittika,01:13:20,03:00:00,Venus,Sun,Jupiter
Taurus,Krittika,03:00:00,05:06:40,Venus,Sun,Saturn
Taurus,Krittika,05:06:40,07:00:00,Venus,Sun,Mercury
Taurus,Krittika,07:00:00,07:46:40,Venus,Sun,Ketu
Taurus,Krittika,07:46:40,10:00:00,Venus,Sun,Venus
Taurus,Rohini,10:00:00,11:06:40,Venus,Moon,Moon
Taurus,Rohini,11:06:40,11:53:20,Venus,Moon,Mars
Taurus,Rohini,11:53:20,13:53:20,Venus,Moon,Rahu
Taurus,Rohini,13:53:20,15:40:00,Venus,Moon,Jupiter
Taurus,Rohini,15:40:00,17:46:40,Venus,Moon,Saturn
Taurus,Rohini,17:46:40,19:40:00,Venus,Moon,Mercury
Taurus,Rohini,19:40:00,20:26:40,Venus,Moon,Ketu
Taurus,Rohini,20:26:40,22:40:00,Venus,Moon,Venus
Taurus,Rohini,22:40:00,23:20:00,Venus,Moon,Sun
Taurus,Mrigashirsha,23:20:00,24:06:40,Venus,Mars,Mars
Taurus,Mrigashirsha,24:06:40,26:06:40,Venus,Mars,Rahu
Taurus,Mrigashirsha,26:06:40,27:53:20,Venus,Mars,Jupiter
Taurus,Mrigashirsha,27:53:20,30:00:00,Venus,Mars,Saturn
Gemini,Mrigashirsha,00:00:00,01:53:20,Mercury,Mars,Mercury
Gemini,Mrigashirsha,01:53:20,02:40:00,Mercury,Mars,Ketu
Gemini,Mrigashirsha,02:40:00,04:53:20,Mercury,Mars,Venus
Gemini,Mrigashirsha,04:53:20,05:33:20,Mercury,Mars,Sun
Gemini,Mrigashirsha,05:33:20,06:40:00,Mercury,Mars,Moon
Gemini,Ardra,06:40:00,08:40:00,Mercury,Rahu,Rahu
Gemini,Ardra,08:40:00,10:26:40,Mercury,Rahu,Jupiter
Gemini,Ardra,10:26:40,12:33:20,Mercury,Rahu,Saturn
Gemini,Ardra,12:33:20,14:26:40,Mercury,Rahu,Mercury
Gemini,Ardra,14:26:40,15:13:20,Mercury,Rahu,Ketu
Gemini,Ardra,15:13:20,17:26:40,Mercury,Rahu,Venus
Gemini,Ardra,17:26:40,18:06:40,Mercury,Rahu,Sun
Gemini,Ardra,18:06:40,19:13:20,Mercury,Rahu,Moon
Gemini,Ardra,19:13:20,20:00:00,Mercury,Rahu,Mars
Gemini,Punarvasu,20:00:00,21:46:40,Mercury,Jupiter,Jupiter
Gemini,Punarvasu,21:46:40,23:53:20,Mercury,Jupiter,Saturn
Gemini,Punarvasu,23:53:20,25:46:40,Mercury,Jupiter,Mercury
Gemini,Punarvasu,25:46:40,26:33:20,Mercury,Jupiter,Ketu
Gemini,Punarvasu,26:33:20,28:46:40,Mercury,Jupiter,Venus
Gemini,Punarvasu,28:46:40,29:26:40,Mercury,Jupiter,Sun
Gemini,Punarvasu,29:26:40,30:00:00,Mercury,Jupiter,Moon
Cancer,Punarvasu,00:00:00,00:33:20,Moon,Jupiter,Moon
Cancer,Punarvasu,00:33:20,01:20:00,Moon,Jupiter,Mars
Cancer,Punarvasu,01:20:00,03:20:00,Moon,Jupiter,Rahu
Cancer,Pushya,03:20:00,05:26:40,Moon,Saturn,Saturn
Cancer,Pushya,05:26:40,07:20:00,Moon,Saturn,Mercury
Cancer,Pushya,07:20:00,08:06:40,Moon,Saturn,Ketu
Cancer,Pushya,08:06:40,10:20:00,Moon,Saturn,Venus
Cancer,Pushya,10:20:00,11:00:00,Moon,Saturn,Sun
Cancer,Pushya,11:00:00,12:06:40,Moon,Saturn,Moon
Cancer,Pushya,12:06:40,12:53:20,Moon,Saturn,Mars
Cancer,Pushya,12:53:20,14:53:20,Moon,Saturn,Rahu
Cancer,Pushya,14:53:20,16:40:00,Moon,Saturn,Jupiter
Cancer,Ashlesha,16:40:00,18:33:20,Moon,Mercury,Mercury
Cancer,Ashlesha,18:33:20,19:20:00,Moon,Mercury,Ketu
Cancer,Ashlesha,19:20:00,21:33:20,Moon,Mercury,Venus
Cancer,Ashlesha,21:33:20,22:13:20,Moon,Mercury,Sun
Cancer,Ashlesha,22:13:20,23:20:00,Moon,Mercury,Moon
Cancer,Ashlesha,23:20:00,24:06:40,Moon,Mercury,Mars
Cancer,Ashlesha,24:06:40,26:06:40,Moon,Mercury,Rahu
Cancer,Ashlesha,26:06:40,27:53:20,Moon,Mercury,Jupiter
Cancer,Ashlesha,27:53:20,30:00:00,Moon,Mercury,Saturn
Leo,Magha,00:00:00,00:46:40,Sun,Ketu,Ketu
Leo,Magha,00:46:40,03:00:00,Sun,Ketu,Venus
Leo,Magha,03:00:00,03:40:00,Sun,Ketu,Sun
Leo,Magha,03:40:00,04:46:40,Sun,Ketu,Moon
Leo,Magha,04:46:40,05:33:20,Sun,Ketu,Mars
Leo,Magha,05:33:20,07:33:20,Sun,Ketu,Rahu
Leo,Magha,07:33:20,09:20:00,Sun,Ketu,Jupiter
Leo,Magha,09:20:00,11:26:40,Sun,Ketu,Saturn
Leo,Magha,11:26:40,13:20:00,Sun,Ketu,Mercury
Leo,PurvaPhalguni,13:20:00,15:33:20,Sun,Venus,Venus
Leo,PurvaPhalguni,15:33:20,16:13:20,Sun,Venus,Sun
Leo,PurvaPhalguni,16:13:20,17:20:00,Sun,Venus,Moon
Leo,PurvaPhalguni,17:20:00,18:06:40,Sun,Venus,Mars
Leo,PurvaPhalguni,18:06:40,20:06:40,Sun,Venus,Rahu
Leo,PurvaPhalguni,20:06:40,21:53:20,Sun,Venus,Jupiter
Leo,PurvaPhalguni,21:53:20,24:00:00,Sun,Venus,Saturn
Leo,PurvaPhalguni,24:00:00,25:53:20,Sun,Venus,Mercury
Leo,PurvaPhalguni,25:53:20,26:40:00,Sun,Venus,Ketu
Leo,UttaraPhalguni,26:40:00,27:20:00,Sun,Sun,Sun
Leo,UttaraPhalguni,27:20:00,28:26:40,Sun,Sun,Moon
Leo,UttaraPhalguni,28:26:40,29:13:20,Sun,Sun,Mars
Leo,UttaraPhalguni,29:13:20,30:00:00,Sun,Sun,Rahu
Virgo,UttaraPhalguni,00:00:00,01:13:20,Mercury,Sun,Rahu
Virgo,UttaraPhalguni,01:13:20,03:00:00,Mercury,Sun,Jupiter
Virgo,UttaraPhalguni,03:00:00,05:06:40,Mercury,Sun,Saturn
Virgo,UttaraPhalguni,05:06:40,07:00:00,Mercury,Sun,Mercury
Virgo,UttaraPhalguni,07:00:00,07:46:40,Mercury,Sun,Ketu
Virgo,UttaraPhalguni,07:46:40,10:00:00,Mercury,Sun,Venus
Virgo,Hasta,10:00:00,11:06:40,Mercury,Moon,Moon
Virgo,Hasta,11:06:40,11:53:20,Mercury,Moon,Mars
Virgo,Hasta,11:53:20,13:53:20,Mercury,Moon,Rahu
Virgo,Hasta,13:53:20,15:40:00,Mercury,Moon,Jupiter
Virgo,Hasta,15:40:00,17:46:40,Mercury,Moon,Saturn
Virgo,Hasta,17:46:40,19:40:00,Mercury,Moon,Mercury
Virgo,Hasta,19:40:00,20:26:40,Mercury,Moon,Ketu
Virgo,Hasta,20:26:40,22:40:00,Mercury,Moon,Venus
Virgo,Hasta,22:40:00,23:20:00,Mercury,Moon,Sun
Virgo,Chitra,23:20:00,24:06:40,Mercury,Mars,Mars
Virgo,Chitra,24:06:40,26:06:40,Mercury,Mars,Rahu
Virgo,Chitra,26:06:40,27:53:20,Mercury,Mars,Jupiter
Virgo,Chitra,27:53:20,30:00:00,Mercury,Mars,Saturn
Libra,Chitra,00:00:00,01:53:20,Venus,Mars,Mercury
Libra,Chitra,01:53:20,02:40:00,Venus,Mars,Ketu
Libra,Chitra,02:40:00,04:53:20,Venus,Mars,Venus
Libra,Chitra,04:53:20,05:33:20,Venus,Mars,Sun
Libra,Chitra,05:33:20,06:40:00,Venus,Mars,Moon
Libra,Svati,06:40:00,08:40:00,Venus,Rahu,Rahu
Libra,Svati,08:40:00,10:26:40,Venus,Rahu,Jupiter
Libra,Svati,10:26:40,12:33:20,Venus,Rahu,Saturn
Libra,Svati,12:33:20,14:26:40,Venus,Rahu,Mercury
Libra,Svati,14:26:40,15:13:20,Venus,Rahu,Ketu
Libra,Svati,15:13:20,17:26:40,Venus,Rahu,Venus
Libra,Svati,17:26:40,18:06:40,Venus,Rahu,Sun
Libra,Svati,18:06:40,19:13:20,Venus,Rahu,Moon
Libra,Svati,19:13:20,20:00:00,Venus,Rahu,Mars
Libra,Vishakha,20:00:00,21:46:40,Venus,Jupiter,Jupiter
Libra,Vishakha,21:46:40,23:53:20,Venus,Jupiter,Saturn
Libra,Vishakha,23:53:20,25:46:40,Venus,Jupiter,Mercury
Libra,Vishakha,25:46:40,26:33:20,Venus,Jupiter,Ketu
Libra,Vishakha,26:33:20,28:46:40,Venus,Jupiter,Venus
Libra,Vishakha,28:46:40,29:26:40,Venus,Jupiter,Sun
Libra,Vishakha,29:26:40,30:00:00,Venus,Jupiter,Moon
Scorpio,Vishakha,00:00:00,00:33:20,Mars,Jupiter,Moon
Scorpio,Vishakha,00:33:20,01:20:00,Mars,Jupiter,Mars
Scorpio,Vishakha,01:20:00,03:20:00,Mars,Jupiter,Rahu
Scorpio,Anuradha,03:20:00,05:26:40,Mars,Saturn,Saturn
Scorpio,Anuradha,05:26:40,07:20:00,Mars,Saturn,Mercury
Scorpio,Anuradha,07:20:00,08:06:40,Mars,Saturn,Ketu
Scorpio,Anuradha,08:06:40,10:20:00,Mars,Saturn,Venus
Scorpio,Anuradha,10:20:00,11:00:00,Mars,Saturn,Sun
Scorpio,Anuradha,11:00:00,12:06:40,Mars,Saturn,Moon
Scorpio,Anuradha,12:06:40,12:53:20,Mars,Saturn,Mars
Scorpio,Anuradha,12:53:20,14:53:20,Mars,Saturn,Rahu
Scorpio,Anuradha,14:53:20,16:40:00,Mars,Saturn,Jupiter
Scorpio,Jyeshtha,16:40:00,18:33:20,Mars,Mercury,Mercury
Scorpio,Jyeshtha,18:33:20,19:20:00,Mars,Mercury,Ketu
Scorpio,Jyeshtha,19:20:00,21:33:20,Mars,Mercury,Venus
Scorpio,Jyeshtha,21:33:20,22:13:20,Mars,Mercury,Sun
Scorpio,Jyeshtha,22:13:20,23:20:00,Mars,Mercury,Moon
Scorpio,Jyeshtha,23:20:00,24:06:40,Mars,Mercury,Mars
Scorpio,Jyeshtha,24:06:40,26:06:40,Mars,Mercury,Rahu
Scorpio,Jyeshtha,26:06:40,27:53:20,Mars,Mercury,Jupiter
Scorpio,Jyeshtha,27:53:20,30:00:00,Mars,Mercury,Saturn
Sagittarius,Mula,00:00:00,00:46:40,Jupiter,Ketu,Ketu
Sagittarius,Mula,00:46:40,03:00:00,Jupiter,Ketu,Venus
Sagittarius,Mula,03:00:00,03:40:00,Jupiter,Ketu,Sun
Sagittarius,Mula,03:40:00,04:46:40,Jupiter,Ketu,Moon
Sagittarius,Mula,04:46:40,05:53:20,Jupiter,Ketu,Mars
Sagittarius,Mula,05:53:20,07:33:20,Jupiter,Ketu,Rahu
Sagittarius,Mula,07:33:20,09:20:00,Jupiter,Ketu,Jupiter
Sagittarius,Mula,09:20:00,11:26:40,Jupiter,Ketu,Saturn
Sagittarius,Mula,11:26:40,13:20:00,Jupiter,Ketu,Mercury
Sagittarius,PurvaAshadha,13:20:00,15:33:20,Jupiter,Venus,Venus
Sagittarius,PurvaAshadha,15:33:20,16:13:20,Jupiter,Venus,Sun
Sagittarius,PurvaAshadha,16:13:20,17:20:00,Jupiter,Venus,Moon
Sagittarius,PurvaAshadha,17:20:00,18:06:40,Jupiter,Venus,Mars
Sagittarius,PurvaAshadha,18:06:40,20:06:40,Jupiter,Venus,Rahu
Sagittarius,PurvaAshadha,20:06:40,21:53:20,Jupiter,Venus,Jupiter
Sagittarius,PurvaAshadha,21:53:20,24:00:00,Jupiter,Venus,Saturn
Sagittarius,PurvaAshadha,24:00:00,25:53:20,Jupiter,Venus,Mercury
Sagittarius,PurvaAshadha,25:53:20,26:40:00,Jupiter,Venus,Ketu
Sagittarius,UttaraAshadha,26:40:00,27:20:00,Jupiter,Sun,Sun
Sagittarius,UttaraAshadha,27:20:00,28:26:40,Jupiter,Sun,Moon
Sagittarius,UttaraAshadha,28:26:40,29:13:20,Jupiter,Sun,Mars
Sagittarius,UttaraAshadha,29:13:20,30:00:00,Jupiter,Sun,Rahu
Capricorn,UttaraAshadha,00:00:00,01:13:20,Saturn,Sun,Rahu
Capricorn,UttaraAshadha,01:13:20,03:00:00,Saturn,Sun,Jupiter
Capricorn,UttaraAshadha,03:00:00,05:06:40,Saturn,Sun,Saturn
Capricorn,UttaraAshadha,05:06:40,07:00:00,Saturn,Sun,Mercury
Capricorn,UttaraAshadha,07:00:00,07:46:40,Saturn,Sun,Ketu
Capricorn,UttaraAshadha,07:46:40,10:00:00,Saturn,Sun,Venus
Capricorn,Shravana,10:00:00,11:06:40,Saturn,Moon,Moon
Capricorn,Shravana,11:06:40,11:53:20,Saturn,Moon,Mars
Capricorn,Shravana,11:53:20,13:53:20,Saturn,Moon,Rahu
Capricorn,Shravana,13:53:20,15:40:00,Saturn,Moon,Jupiter
Capricorn,Shravana,15:40:00,17:46:40,Saturn,Moon,Saturn
Capricorn,Shravana,17:46:40,19:40:00,Saturn,Moon,Mercury
Capricorn,Shravana,19:40:00,20:46:40,Saturn,Moon,Ketu
Capricorn,Shravana,20:46:40,22:40:00,Saturn,Moon,Venus
Capricorn,Shravana,22:40:00,23:20:00,Saturn,Moon,Sun
Capricorn,Dhanishta,23:20:00,24:06:40,Saturn,Mars,Mars
Capricorn,Dhanishta,24:06:40,26:06:40,Saturn,Mars,Rahu
Capricorn,Dhanishta,26:06:40,27:53:20,Saturn,Mars,Jupiter
Capricorn,Dhanishta,27:53:20,30:00:00,Saturn,Mars,Saturn
Aquarius,Dhanishta,00:00:00,01:53:20,Saturn,Mars,Mercury
Aquarius,Dhanishta,01:53:20,02:40:00,Saturn,Mars,Ketu
Aquarius,Dhanishta,02:40:00,04:53:20,Saturn,Mars,Venus
Aquarius,Dhanishta,04:53:20,05:33:20,Saturn,Mars,Sun
Aquarius,Dhanishta,05:33:20,06:40:00,Saturn,Mars,Moon
Aquarius,Shatabhisha,06:40:00,08:40:00,Saturn,Rahu,Rahu
Aquarius,Shatabhisha,08:40:00,10:26:40,Saturn,Rahu,Jupiter
Aquarius,Shatabhisha,10:26:40,12:33:20,Saturn,Rahu,Saturn
Aquarius,Shatabhisha,12:33:20,14:26:40,Saturn,Rahu,Mercury
Aquarius,Shatabhisha,14:26:40,15:13:20,Saturn,Rahu,Ketu
Aquarius,Shatabhisha,15:13:20,17:26:40,Saturn,Rahu,Venus
Aquarius,Shatabhisha,17:26:40,18:06:40,Saturn,Rahu,Sun
Aquarius,Shatabhisha,18:06:40,19:13:20,Saturn,Rahu,Moon
Aquarius,Shatabhisha,19:13:20,20:00:00,Saturn,Rahu,Mars
Aquarius,PurvaBhadrapada,20:00:00,21:46:40,Saturn,Jupiter,Jupiter
Aquarius,PurvaBhadrapada,21:46:40,23:53:20,Saturn,Jupiter,Saturn
Aquarius,PurvaBhadrapada,23:53:20,25:46:40,Saturn,Jupiter,Mercury
Aquarius,PurvaBhadrapada,25:46:40,26:33:20,Saturn,Jupiter,Ketu
Aquarius,PurvaBhadrapada,26:33:20,28:46:40,Saturn,Jupiter,Venus
Aquarius,PurvaBhadrapada,28:46:40,29:26:40,Saturn,Jupiter,Sun
Aquarius,PurvaBhadrapada,29:26:40,30:00:00,Saturn,Jupiter,Moon
Pisces,PurvaBhadrapada,00:00:00,00:33:20,Jupiter,Jupiter,Moon
Pisces,PurvaBhadrapada,00:33:20,01:20:00,Jupiter,Jupiter,Mars
Pisces,PurvaBhadrapada,01:20:00,03:20:00,Jupiter,Jupiter,Rahu
Pisces,UttaraBhadrapada,03:20:00,05:26:40,Jupiter,Saturn,Saturn
Pisces,UttaraBhadrapada,05:26:40,07:20:00,Jupiter,Saturn,Mercury
Pisces,UttaraBhadrapada,07:20:00,08:06:40,Jupiter,Saturn,Ketu
Pisces,UttaraBhadrapada,08:06:40,10:20:00,Jupiter,Saturn,Venus
Pisces,UttaraBhadrapada,10:20:00,11:00:00,Jupiter,Saturn,Sun
Pisces,UttaraBhadrapada,11:00:00,12:06:40,Jupiter,Saturn,Moon
Pisces,UttaraBhadrapada,12:06:40,12:53:20,Jupiter,Saturn,Mars
Pisces,UttaraBhadrapada,12:53:20,14:53:20,Jupiter,Saturn,Rahu
Pisces,UttaraBhadrapada,14:53:20,16:40:00,Jupiter,Saturn,Jupiter
Pisces,Revati,16:40:00,18:33:20,Jupiter,Mercury,Mercury
Pisces,Revati,18:33:20,19:20:00,Jupiter,Mercury,Ketu
Pisces,Revati,19:20:00,21:33:20,Jupiter,Mercury,Venus
Pisces,Revati,21:33:20,22:13:20,Jupiter,Mercury,Sun
Pisces,Revati,22:13:20,23:20:00,Jupiter,Mercury,Moon
Pisces,Revati,23:20:00,24:06:40,Jupiter,Mercury,Mars
Pisces,Revati,24:06:40,26:06:40,Jupiter,Mercury,Rahu
Pisces,Revati,26:06:40,27:53:20,Jupiter,Mercury,Jupiter
Pisces,Revati,27:53:20,30:00:00,Jupiter,Mercury,Saturn

**Comment by diliprk** [comment]
I prefer diatrics and romanized sanskrit in the sign and nakshatra names, if you have corrected the degrees, please raise a pull request on the csv file and I can inspect whether to merge
